---
- name: Delete HBAC rule in freeipa 
  hosts: "{{ all | default('ipaserver') }}"
  become: false
  vars_files: ../vault.yml
  tasks:
    - name: delete a HBAC rule
      ipahbacrule:
        ipaadmin_principal: "{{ idm_ops_admin_username | default(omit) }}"
        ipaadmin_password: "{{ idm_ops_admin_password }}"
        name: "{{ ipa_hbac_rule_name }}"
        state: absent