---
- name: Add a user to a group in our IDM instance
  hosts: '{{ target | default("ipaserver") }}'
  tasks:
    - name: Add user to IDM group
      redhat.rhel_idm.ipagroup:
        name: "{{ idm_ops_group_name }}"
        user:
          - "{{ idm_ops_user_name }}"
        action: member
