---
- name: Add a group to a group in our IDM instance
  hosts: '{{ target | default("ipaserver") }}'
  tasks:
    - name: Add group to IDM group
      redhat.rhel_idm.ipagroup:
        name: "{{ idm_ops_group_name }}"
        group:
          - "{{ idm_ops_groupadd_name }}"
        action: group
