---
- name: Create a group in IDM
  hosts: '{{ target | default("ipaserver") }}'
  become: false
  tasks:
    - name: Create an IDM group
      redhat.rhel_idm.ipagroup:
        name: "{{ idm_ops_group_name }}"
...
