---
- name: Create or update a sudo rule in our IDM instance
  hosts: "{{ all | default('ipaserver') }}"
  become: false
  vars_files: ../vault.yml
  tasks:
    - name: Create or update an IDM sudo rule
      redhat.rhel_idm.ipasudorule:
        ipaadmin_principal: "{{ idm_ops_admin_username | default(omit) }}"
        ipaadmin_password: "{{ idm_ops_admin_password }}"
        name: "{{ idm_ops_sudo_rule }}"
        allow_sudocmdgroup: "{{ idm_ops_sudo_cmd_group }}"
        group: "{{ idm_ops_group_name }}"
        hostgroup: "{{ idm_ops_hbac_hostgroup_name }}"
        runasusercategory: "all"
        runasgroupcategory: "all"
