---
- name: Create a sudo command group in our IDM instance
  hosts: '{{ target | default("ipaserver") }}'
  become: false
  tasks:
    - name: Create an IDM sudo command group
      redhat.rhel_idm.ipasudocmdgroup:
        name: "{{ idm_ops_sudo_cmd_group }}"
    - name: Add a command to sudo command group
      redhat.rhel_idm.ipasudocmdgroup:
        name: "{{ idm_ops_sudo_cmd_group }}"
        sudocmd: "{{ idm_ops_sudo_command }}"
        action: member
