---
- name: Create a group in IDM
  hosts: '{{ target | default("ipaserver") }}'
  become: false
  vars_files: ../vault.yml
  tasks:
    - name: Create an IDM group
      redhat.rhel_idm.ipagroup:
        ipaadmin_principal: "{{ idm_ops_admin_username | default(omit) }}"
        ipaadmin_password: "{{ idm_ops_admin_password }}"
        name: "{{ idm_ops_group_name }}"
...
