---
- name: Delete a host from IDM
  hosts: '{{ ipaserver | default("sat_hostcollection_idmserver") }}'
  become: false
  tasks:
    - name: Ensure IDM Host is Absent
      redhat.rhel_idm.ipahost:
        name: "{{ vm_name }}"
        state: absent
        update_dns: true
