---
- name: Delete a sudo command group in our IDM instance
  hosts: "{{ all | default('ipaserver') }}"
  become: false
  vars_files: ../vault.yml
  tasks:
    - name: Delete an IDM sudo command group
      redhat.rhel_idm.ipasudocmdgroup:
        ipaadmin_principal: "{{ idm_ops_admin_username | default(omit) }}"
        ipaadmin_password: "{{ idm_ops_admin_password }}"
        name: "{{ idm_ops_sudo_cmd_group }}"
        state: absent
