---
- name: Delete a sudo rule in our IDM instance
  hosts: '{{ target | default("ipaserver") }}'
  become: false
  vars_files: ../vault.yml
  tasks:
    - name: Delete an IDM sudo rule
      redhat.rhel_idm.ipasudorule:
        name: "{{ idm_ops_sudo_rule }}"
        state: absent
