---
- name: Delete a sudo command group in our IDM instance
  hosts: '{{ target | default("ipaserver") }}'
  become: false
  vars_files: ../vault.yml
  tasks:
    - name: Delete an IDM sudo command group
      redhat.rhel_idm.ipasudocmdgroup:
        name: "{{ idm_ops_sudo_cmd_group }}"
        state: absent
