---
- name: Delete HBAC rule in IDM
  hosts: '{{ target | default("ipaserver") }}'
  become: false
  vars_files: ../vault.yml
  tasks:
    - name: Delete a HBAC rule
      redhat.rhel_idm.ipahbacrule:
        name: "{{ idm_ops_hbac_rule_name }}"
        state: absent
