---
- name: Delete a group in our IDM instance
  hosts: '{{ target | default("ipaserver") }}'
  become: false
  tasks:
    - name: Delete an IDM Group
      redhat.rhel_idm.ipagroup:
        name: "{{ idm_ops_group_name }}"
        state: absent
...
