---
- name: Remove and delete a user in our IDM instance
  hosts: '{{ target | default("ipaserver") }}'
  become: false
  tasks:
    - name: Remove an IDM User
      redhat.rhel_idm.ipauser:
        ipaadmin_password: "{{ idm_ops_admin_password }}"
        name: "{{ idm_ops_user_name }}"
        state: absent
