---
- name: Enable a disabled user in our IDM instance
  hosts: '{{ target | default("ipaserver") }}'
  become: false
  vars_files: ../vault.yml
  tasks:
    - name: Enable an IDM User
      redhat.rhel_idm.ipauser:
        name: "{{ idm_ops_user_name }}"
        state: enabled
