---
- name: Expire the sssd cache and restart sssd
  hosts: all
  tasks:
    - name: Expire the sssd cache
      ansible.builtin.command:
        cmd: 'sss_cache -E'
      changed_when: true
    - name: Restart sssd
      ansible.builtin.service:
        name: sssd
        state: restarted
