---
- name: Reset a user password in our IDM instance
  hosts: '{{ target | default("ipaserver") }}'
  become: false
  vars_files: ../vault.yml
  tasks:
    - name: Reset a user password
      redhat.rhel_idm.ipauser:
        name: "{{ idm_ops_user_name }}"
        random: true
        update_password: always
